defaults:
  - _self_

experiment_name: mnist_diffusion
device: cuda

generative_model:
  _target_: emgen.generative_model.diffusion.diffusion_model.DiffusionModel
  device: ${device}

  noise_scheduler:
    _target_: emgen.generative_model.diffusion.noise_scheduler.NoiseScheduler
    device: ${device}
    num_timesteps: 1000

  diffusion_arch:
    _target_: emgen.generative_model.diffusion.diffusion_model_arch.UNetArch
    device: ${device}
    in_channels: 1
    base_channels: 64
    num_down: 2

  dataset:
    _target_: emgen.dataset.mnist.MNISTDataset
    train: true

  train:
    train_batch_size: 64
    eval_batch_size: 64
    num_epochs: 50
    learning_rate: 1e-4
    save_images_step: 5

